#!/bin/sh

# CLI argument: base directory (default ~)

export SCRIPT_DIR="$(dirname "$(realpath "$0")")"

export BASE_DIR=${1:~}
. $SCRIPT_DIR/env

ln -s $SCRIPT_DIR/gitui $XDG_CONFIG_HOME/gitui
ln -s $SCRIPT_DIR/latexmk $XDG_CONFIG_HOME/latexmk
ln -s $SCRIPT_DIR/neomutt $XDG_CONFIG_HOME/neomutt
ln -s $SCRIPT_DIR/nvim $XDG_CONFIG_HOME/nvim
ln -s $SCRIPT_DIR/wezterm $XDG_CONFIG_HOME/wezterm
ln -s $SCRIPT_DIR/ripgreprc $XDG_CONFIG_HOME/ripgreprc

mkdir -p $XDG_CONFIG_HOME/git
ln -s $SCRIPT_DIR/gitconfig $XDG_CONFIG_HOME/git/config

echo "export BASE_DIR=\"$BASE_DIR\"" >> ~/.zshrc
echo "source \"$SCRIPT_DIR/zshrc\"" >> ~/.zshrc
echo "" >> ~/.zshrc

echo Install zsh, nvim, clangd, ripgrep, latex stuff, neomutt, w3m, wezterm, \
    bat, delta, git manually

