#!/bin/zsh

# Use this script to set up the shell (call from .zshrc)
# Set the BASE_DIR env variable before sourcing

# Prevent esc+key from registering as alt+key
KEYTIMEOUT=1

script_dir="$(dirname "$0")"
source $script_dir/env

# History stuff
setopt IGNORE_EOF
setopt APPEND_HISTORY

setopt histignorealldups sharehistory

HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.zsh_history

# Completion
eval $(dircolors -b $script_dir/.dircolors)
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'

zstyle ':completion:*:warnings' format '%B%F{red}No matches!%f%b'

zstyle ':completion:*:*:*:commands' list-colors '=(#b)(*)=36'
zstyle ':completion:*:*:*:options' list-colors '=(#b)(--*)=35'

if [[ -d /c ]] then
    # Make C drive completion work on msys2
    zstyle ':completion:*' fake-files /: '/:c'

    # Force forward slashes on windows
    alias fd='fd --path-separator=//'
fi

# Nicer prompt
setopt prompt_subst
PROMPT='%F{green}%n %F{blue}%~%f %# '
RPROMPT='%F{%(?.green.red)}%?  %f%F{yellow}%*%f'

# Next few sections are copied from the msys2 .bashrc
# Interactive operation...
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Default to human readable figures
alias df='df -h'
alias du='du -h'

# Misc :)
alias less='less -r'
alias grep='grep --color'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# Some shortcuts for different directory listings
alias ls='ls -hF --color=tty'
alias dir='ls --color=auto --format=vertical'
alias vdir='ls --color=auto --format=long'
alias ll='ls -l'
alias la='ls -A'
alias l='ls -CF'

# Quickly run programs sent from nvim
if [[ -n "$QUICK_PROG" ]]; then
  alias p="$QUICK_PROG"
fi

bindkey -v

source <(fzf --zsh)

# fzf env variables
fzf-env-widget() {
  local selected
  selected=$(print -l ${(k)parameters} | fzf) || return
  LBUFFER+="$selected"
  zle redisplay
}
zle -N fzf-env-widget
bindkey '^E' fzf-env-widget

